steps:
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']
  dir: 'src/me/bq_app/frontend'
- name: 'node:18'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'src/me/bq_app/frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'src/me/bq_app/frontend/build', 'gs://bq-app-frontend-bucket']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['web', 'set', '-m', 'index.html', '-e', 'index.html', 'gs://bq-app-frontend-bucket']