version: '3.8'

services:
  backend:
    build: ./implementation/backend
    ports:
      - "8000:8000"
    volumes:
      - ./implementation/backend/recommendations.json:/app/recommendations.json

  frontend:
    build:
      context: ./implementation
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
